
--CONSULTAS 
----Consultar un histórico de costo de servicios cobrado por institución 
SELECT EXTRACT(YEAR FROM FECHA_DEL_SERVICIO),TIPO_DE_SERVICOS,COSTO_DE_SERVICOS 
FROM SERVICIO;
----Consultar un histórico de atención por doctor 
SELECT EXTRACT(YEAR FROM FECHA_DEL_REVISION),doctor.NOMBRE, PERSONA_DE_TERCERA_EDAD.nombre FROM REVISION_MEDICAS 
INNER JOIN DOCTORES_REVICIONES  ON REVISION_MEDICAS.ID_REVICION = DOCTORES_REVICIONES.FKEY_ID_REVICION
INNER JOIN DOCTOR  ON DOCTOR.ID_DOCTOR = DOCTORES_REVICIONES.FKEY_ID_DOCTOR
INNER JOIN PERSONA_REVICIONES  ON REVISION_MEDICAS.ID_REVICION = PERSONA_REVICIONES.FKE_ID_REVICION
INNER JOIN  PERSONA_DE_TERCERA_EDAD  ON  PERSONA_DE_TERCERA_EDAD.CEDULA = PERSONA_REVICIONES.FKE_CEDULA;
-----Consultar un histórico de atención por doctor 
SELECT  EXTRACT(YEAR FROM FECHA_DEL_TRATAMIENTO),DOCTOR.NOMBRE,TIPO_DE_TRATAMIENTO FROM TRATAMIENTO 
INNER JOIN DOCTORES_TRATAMIENTO ON TRATAMIENTO.ID_TRATAMIENTO = DOCTORES_TRATAMIENTO.FK_ID_TRATAMIENTO
INNER JOIN DOCTOR  ON DOCTOR.ID_DOCTOR = DOCTORES_TRATAMIENTO.FK_ID_DOCTOR;
----Consultar el histórico del evento que tuvo más éxito
SELECT EXTRACT(YEAR FROM FECHA_DEL_EVENTO), TIPO_DE_EVENTO,NUMERO_DE_PERSONA FROM  EVENTO
WHERE EVENTO.NUMERO_DE_PERSONA >=50;

