  
--CURSOR
SET SERVEROUTPUT ON;
DECLARE 
    CURSOR CU_SERVICIOS IS SELECT  EXTRACT(YEAR FROM SERVICIO.FECHA_DEL_SERVICIO) AS AÑO,COUNT(PERSONA_DE_TERCERA_EDAD.CEDULA) AS CANTIDAD,
    GENERO.TIPO_GENERO,GENERO.ID_GENERO, TIPO_DE_SERVICOS FROM SERVICIO 
    INNER JOIN DETALLES_DE_FACTURA ON SERVICIO.ID_SERVICIO =  DETALLES_DE_FACTURA.FK_ID_SERVICIO
    INNER JOIN PLANTILLA_DE_INGRESO ON PLANTILLA_DE_INGRESO.ID_PLANTILLA = DETALLES_DE_FACTURA.FKY_ID_PANTILLA
    INNER JOIN PERSONA_DE_TERCERA_EDAD ON PERSONA_DE_TERCERA_EDAD.CEDULA = PLANTILLA_DE_INGRESO.FKY_CEDULA
    INNER JOIN GENERO ON GENERO.ID_GENERO = PERSONA_DE_TERCERA_EDAD.FKE_ID_GENERO
    GROUP BY GENERO.ID_GENERO,SERVICIO.FECHA_DEL_SERVICIO,GENERO.TIPO_GENERO,SERVICIO.TIPO_DE_SERVICOS;
    COUNTE INT;
BEGIN 
    COUNTE:=0;
    FOR CONT_F IN CU_SERVICIOS LOOP 
    COUNTE:=  COUNTE+CONT_F.CANTIDAD;
    dbms_output.put_line('AÑO '||CONT_F.AÑO ||' Cantidad '||CONT_F.CANTIDAD||' Tipo de genero '||CONT_F.TIPO_GENERO|| ' Id de genero '||
    CONT_F.ID_GENERO|| 'Tipo de servicio'||CONT_F.TIPO_DE_SERVICOS);
    end loop;
    dbms_output.put_line('Cantidad de hombres y mujeres fueron: ' || COUNTE);
END;
